#!/usr/bin/env python3

import argparse
import http.client
import sys

FLAGS = None

DEFAULT_PORT = 5567

def exec(cmd: list[str]) -> int:
  returncode = 1
  headers = {}
  if FLAGS.cwd:
    headers['CWD'] = FLAGS.cwd
  encoded_cmd = []
  for arg in cmd_args:
    encoded_cmd.append(bytes.hex(arg.encode()))
  try:
    conn = http.client.HTTPConnection('localhost', FLAGS.port)
    conn.request('POST', '/', headers=headers, body=':'.join(encoded_cmd))
    res = conn.getresponse()
    if res.status != http.client.OK:
      sys.stderr.write(res.reason)
      return
    for line in res:
      line = line.decode()
      if line.startswith('STDOUT:'):
        sys.stdout.write(bytes.fromhex(line[7:]).decode())
      elif line.startswith('STDERR:'):
        sys.stderr.write(bytes.fromhex(line[7:]).decode())
      elif line.startswith('CODE:'):
        returncode = int(bytes.fromhex(line[5:]).decode())
  finally:
    conn.close()
  return returncode
  

if __name__ == "__main__":
  all_args = sys.argv[1:]
  parser = argparse.ArgumentParser(description="Remote exec client sends command to remote server.")
  parser.add_argument('-c', '--cwd', metavar='', type=str, help="Sets working directory on remote server to run command", default=None)
  parser.add_argument('-p', '--port', metavar='', type=int, help="Remote exec server port", default=DEFAULT_PORT)
  internal_args = []
  cmd_args = []

  if '--' not in all_args:
    parser.parse_args() # Just to print help
    raise ValueError('Usage error, use -h/--help to know more')
  split_idx = all_args.index('--')
  internal_args = all_args[:split_idx]
  cmd_args = all_args[split_idx+1:]
  FLAGS = parser.parse_args(internal_args)
  sys.exit(exec(cmd_args))
